# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
 
trigger:
- master
 
pool:
  vmImage: 'windows-latest'

# Set variables
variables:
  directory: artwork-website
  stage: production
  serviceConnection: 692d4aeb-719e-4f83-8e8e-5c16ea3d9cd0
  appServiceName: lizamorrison
 
jobs:
  - job: 
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'
    
    - script: 
        npm install
      displayName: 'npm install'
      workingDirectory: $(directory)
    
    - script: 
        set "REACT_APP_STAGE=$(stage)" && npm run build
      displayName: 'npm build'
      workingDirectory: $(directory)
    
    - task: CopyFiles@2
      displayName: 'Copy files'
      inputs:
        sourceFolder: '$(directory)/dist' 
        Contents: '**/*'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
        cleanTargetFolder: true
    
    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true
    
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Build Artifacts'
      inputs: 
        pathtoPublish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
    
    - task: AzureWebApp@1
      displayName: 'Deploy to App Service'
      inputs:
        azureSubscription: '$(serviceConnection)'
        appName: '$(appServiceName)'
        appType: 'webApp'
        package: '$(System.ArtifactsDirectory)/$(Build.BuildId).zip'